[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#38BDF8"
backgroundColor = "#0A0E17"
secondaryBackgroundColor = "#111827"
textColor = "#F8FAFC"
